-- DROP TABLE
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS userdetails;

DROP SEQUENCE USERDETAILS_SEQ;
CREATE SEQUENCE USERDETAILS_SEQ START WITH 1 INCREMENT BY 1;

-- Create the USERDETAILS table
CREATE TABLE IF NOT EXISTS userdetails (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(10) NOT NULL UNIQUE,
    first_name VARCHAR(10) NOT NULL,
    last_name VARCHAR(10) NOT NULL,
    email_address VARCHAR(20) NOT NULL,
    role VARCHAR(10) NOT NULL,
    ssn VARCHAR(10) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS orders (
  order_Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_Description VARCHAR(255),
  user_Id BIGINT NOT NULL,
  FOREIGN KEY (user_Id) REFERENCES userdetails(id) ON DELETE CASCADE
);
